CONFIG_ZMK_KEYBOARD_NAME="Corne Derecho"
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_PERIPHERAL_HID_INDICATORS=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y