 # name for the bluetooth
CONFIG_ZMK_KEYBOARD_NAME="Corne Derecho"

# define the right as the master
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# turn on the zmk studio
CONFIG_ZMK_STUDIO=y

# turn on the display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Communication bluetooth
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
